apiVersion: v1
kind: ConfigMap
metadata:
  name: vault
  labels:
    app: vault
data:
  vault-addr: "http://127.0.0.1:8200"
  setting.hcl: |
    storage "file" {
      path = "/mnt/vault/data"
    }
  
    listener "tcp" {
     address = "127.0.0.1:8200"
     tls_disable = 1
    }
