apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: "vault:1.0.1"
          imagePullPolicy: IfNotPresent
          command:
            - vault
            - server
            - -config=/settings/setting.hcl
          env:
            - name: VAULT_API_ADDR
              valueFrom:
                configMapKeyRef:
                  key: vault-addr
                  name: vault
          ports:
            - containerPort: 8200
              name: vault
              protocol: TCP
          volumeMounts:
            - mountPath: /settings
              name: settings
            - mountPath: /mnt/vault/data
              name: data
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
      volumes:
        - name: settings
          configMap:
            name: vault
            items:
              - key: setting.hcl
                path: setting.hcl
        - name: data
          hostPath:
            path: /tmp/vault/data
            type: DirectoryOrCreate
