apiVersion: v1
kind: ConfigMap
metadata:
  name: concourse-web
  labels:
    app: concourse-web
data:
#  postgres-host: "10.107.145.4"
  external-url: "http://localhost:8080"
  vault-host: vault
  vault-port: "8200"
  vault-auth-backend: approle
  vault-insecure-skip-verify: "true"
  prometheus-bind-ip: "0.0.0.0"
  prometheus-bind-port: "9391"
