apiVersion: v1
kind: Secret
metadata:
  name: concourse-web
  labels:
    app: concourse-web
type: Opaque
data:
  local-users: "dGVzdDokMmEkMTAkc0RCNkFzSDJIaGVPV0hJTHJuSFZKT0NacS9HWXRVWUUwMnlwSkpUUUJtV0pOaXZZTmhQM3k="
