apiVersion: v1
kind: Service
metadata:
  name: concourse-web
  labels:
    app: concourse-web
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      name: atc
      targetPort: atc
    - port: 2222
      name: tsa
      targetPort: tsa
  selector:
    app: concourse-web
