apiVersion: v1
kind: ConfigMap
metadata:
  name: concourse-postgresql
  labels:
    app: concourse-postgresql
data:
  postgres-user: concourse
  postgres-db: concourse
  postgres-initdb-args: ""
  pguser: concourse
  pgdata: /var/lib/postgresql/data/pgdata
