apiVersion: apps/v1
kind: Deployment
metadata:
  name: concourse-postgresql
  labels:
    app: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: concourse-postgresql
          image: "postgres:9.6.2"
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: concourse-postgres
                  key: postgres-user
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  name: concourse-postgres
                  key: pguser
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: concourse-postgres
                  key: postgres-db
            - name: POSTGRES_INITDB_ARGS
              valueFrom:
                configMapKeyRef:
                  name: concourse-postgres
                  key: postgres-initdb-args
            - name: PGDATA
              valueFrom:
                configMapKeyRef:
                  name: concourse-postgres
                  key: pgdata
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres-password
                  name: concourse-postgresql
          ports:
            - containerPort: 5432
              name: postgresql
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
