apiVersion: apps/v1
kind: Deployment
metadata:
  name: concourse-postgresql
  labels:
    app: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: concourse-postgresql
          image: "postgres:9.6.2"
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: "concourse"
            - name: PGUSER
              value: "concourse"
            - name: POSTGRES_DB
              value: "concourse"
            - name: POSTGRES_INITDB_ARGS
              value: ""
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres-password
                  name: concourse-postgresql
          ports:
            - containerPort: 5432
              name: postgresql
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
