apiVersion: v1
kind: Service
metadata:
  name: concourse-postgres
  labels:
    app: postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      name: postgresql
      targetPort: postgresql
  selector:
    app: postgresql
